const data = {
  products: [
    {
      _id: '1',
      name: 'Worlds',
      category: 'Music',
      image: '/images/p1.jpg',
      price: 17.99,
      artist: 'Porter Robinson',
      rating: 5,
      numReviews: 100,
      description: 'Best Album ever',
    },
    {
      _id: '2',
      name: 'Adventure',
      category: 'Music',
      image: '/images/p2.jpg',
      price: 41.87,
      artist: 'Madeon',
      rating: 4.5,
      numReviews: 100,
      description: 'Awesome album',
    },
    {
      _id: '3',
      name: 'Good Faith',
      category: 'Music',
      image: '/images/p3.jpg',
      price: 9.99,
      artist: 'Madeon',
      rating: 5,
      numReviews: 100,
      description: 'Best Album ever',
    },
    {
      _id: '4',
      name: 'Discovery',
      category: 'Music',
      image: '/images/p4.jpg',
      price: 99.99,
      artist: 'Daft Punk',
      rating: 4.5,
      numReviews: 100,
      description: 'One of the greatest albums',
    },
    {
      _id: '5',
      name: 'Stories',
      category: 'Music',
      image: '/images/p5.jpg',
      price: 13.29,
      artist: 'Avicii',
      rating: 5,
      numReviews: 100,
      description: 'Very nice album',
    },
    {
      _id: '6',
      name: 'Voicenotes',
      category: 'Music',
      image: '/images/p6.jpg',
      price: 11.88,
      artist: 'Charlie Puth',
      rating: 4,
      numReviews: 100,
      description: 'Very nice album',
    },
  ]
}

export default data;