export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const SUCCESS_PRODUCT_REQUEST = "SUCCESS_PRODUCT_REQUEST";
export const FAIL_PRODUCT_REQUEST = "FAIL_PRODUCT_REQUEST";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const SUCCESS_PRODUCT_DETAIL = "SUCCESS_PRODUCT_DETAIL";
export const FAIL_PRODUCT_DETAIL = "FAIL_RPDOCUT_DETAIL";

export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const CART_SAVE_SHPIPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
