export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const SUCCESS_PRODUCT_REQUEST = "SUCCESS_PRODUCT_REQUEST";
export const FAIL_PRODUCT_REQUEST = "FAIL_PRODUCT_REQUEST";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const SUCCESS_PRODUCT_DETAIL = "SUCCESS_PRODUCT_DETAIL";
export const FAIL_PRODUCT_DETAIL = "FAIL_RPDOCUT_DETAIL";

export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";

